### ISSUE TITLE
Add TODO for Intention/Inspection/Quickfix

### ISSUE THREAD

**Issue by shiraji** [MokMokKotlinContributeJP/kontribute-tips#1]
I want to introduce what we need to do for adding new features for Intention/Inspection/Quickfix

Could you help me how to add these information to this project?

### Intention

* idea/src/org/jetbrains/kotlin/idea/intentions/XxxIntention.ktを追加
* idea/src/META-INF/plugin.xmlにintentionActionタグを追加
* idea/resources/intentionDescriptions/XxxIntention/description.htmlにIntentionの説明を追加
* idea/resources/intentionDescriptions/XxxIntention/before.kt.templateとidea/resources/intentionDescriptions/XxxIntention/after.kt.templateを追加
* idea/testData/intentions/xxxにテストデータを作成

### Inspection

* idea/src/org/jetbrains/kotlin/idea/inspections/にXxxInspection.ktを追加
* idea/src/META-INF/plugin.xmlにlocalInspectionのタグを追加
* idea/resources/inspectionDescriptions/Xxx.htmlのInspectionの説明を追加
* idea/testData/inspectionsLocal/xxxにテストデータを作成

### Quickfix

* idea/src/org/jetbrains/kotlin/idea/quickfix/XxxFix.ktを作成する
* idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.ktの対象のエラーにregisterする
* idea/testData/quickfix/xxxにテストデータを作成

(Xxxはそれぞれの名前です。)

**Comment by takahirom** [comment]
Thank you for very useful information!
If you want, You can commit to index.md by following methods. 
* You can directly commit by becoming member. 
* You can send pull request.
